### ISSUE TITLE
Assertions - support also other selectors

### ISSUE THREAD

**Issue by vasilischatziathanasiou** [AuthEceSoftEng/web-recorder-chrome-plugin#2]
Hi,

one first issue that I noticed is that in the assertions, selectors like
"by.cssContainingText" are not supported.

**Comment by dimitrisniras** [comment]
Hi @vasilischatziathanasiou ,

I am using jquery.dom-outline-1.0.js library and containing text assertion is not currently available. However you can edit the test from website and add the text you want.

**Comment by vasilischatziathanasiou** [comment]
@dimitrisniras 

Could you be more specific? For example i am currently using the following assertions in protractor to verify specific output fields in the app.

	
		var verifyProjPrice = function () {
			return browser.isElementPresent(by.cssContainingText('.ng-binding', '332,256.00'));
		}
		browser.wait(verifyProjPrice, 5*1000, 'Total Project Price is incorrect');

		var verifyIRR = function () {
			return browser.isElementPresent(by.cssContainingText('.ng-binding', '13.82'));
		}
		browser.wait(verifyIRR, 5*1000, 'IRR is incorrect');

		var verifyNPV = function () {
			return browser.isElementPresent(by.cssContainingText('.ng-binding', '38,324.94'));
		}
		browser.wait(verifyNPV, 5*1000, 'NPV is incorrect');


How can i add the above assertions from the website?

BRs
Vasilis

**Comment by dimitrisniras** [comment]
From the chrome extension you can specify the filed you want to make the assertion. The default is 'Element is present'. Now if you want a different type of assertion you must go to "http://snf-750380.vm.okeanos.grnet.gr:8080/dashboard/suites/<your-suite>/tests/<your-test>/edit" and in the assertion step you must change the assertion type. You must follow this procedure every time you want an assertion different to "Element is present".
