### ISSUE TITLE
Test is saved in the wrong test suite

### ISSUE THREAD

**Issue by vasilischatziathanasiou** [AuthEceSoftEng/web-recorder-chrome-plugin#5]
Although that the test case is saved from the web recorder in a test suite, the test case is found in another test suite.

More specifically, in the dashboard 3 test suites exist: 

- Commons
- eQuad
- eQuad local host

even though that the test case is saved in the eQuad local host, it appears in the eQuad. 
Note: The only difference between the eQuad and the eQuad local host suite is that the eQuad is scheduled to run daily.

**Comment by dimitrisniras** [comment]
Hi @vasilischatziathanasiou ,

You have to put a dash or an underscore or you can use Camelcase instead of spaces between the words.
